### ISSUE TITLE
line 341: urxvt: command not found

### ISSUE THREAD

**Issue by Mouvedia** [omnesia0rg/got#1]
By what urxvt should be replaced on macOS?

**Comment by ltOgt** [comment]
I am so sorry, never noticed this until now.

Seems like urxvt is not available for os x, but you can replace that line with any terminal you like as long as it can be started with a default path somehow.
If it can't than you wont be able to use this option of the script.

Just replace the `urxvt` in `urxvt -cd $currPath &` with the name of your terminal and `-cd` with the appropriate option of your terminal to start it with the path.
